# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f30f8b2df0b9bcd629704388d9e32dfb27cbfc805d910f57b0fef5ff7a8653d0822a4f3e60d984d70e8268b6223b92b631082e87cae772d755207e0b4600ead9

test:
  secret_key_base: 110d53321a10b58b04a8bd77ba8a91ebc32b9ea43f9221329eefae96333a487fa62ae426eef69a035d4dbefa1c6a7483dd2310d8cc160cedb89c863abc53fd76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
